import './style.css';
import { setupCounter } from './counter.ts';

// Auto generated by Vite

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
<div>
    <h1>Vite + TypeScript + Signals</h1>
    <div class="card">
      <button id="counter" type="button"></button>
      <pre>Here's the snippet for the counter:</pre>
    </div>
  </div>
`;



setupCounter(document.querySelector<HTMLButtonElement>('#counter')!);
