import './style.css';
import { setupCounter } from './counter.ts';

// Auto generated by Vite

const app = document.querySelector<HTMLDivElement>('#app');

if (!app) {
  throw new Error('The app element is missing from the document');
} else {
  app.innerHTML = `
  <div>
      <h1>Vite + TypeScript + Signals</h1>
      <a href="https://github.com/tzachbon/signal-effect" target="_blank">GitHub</a>
      |
      <a href="https://www.npmjs.com/package/signal-effect" target="_blank">NPM</a>
      <div class="card">
        <p>Click the button to increment the counter:</p>
        <button id="counter" type="button"></button>
        <pre>Here's the snippet for the counter:</pre>
      </div>
    </div>
  `;

  const counter = document.querySelector<HTMLButtonElement>('#counter');

  if (!counter) {
    throw new Error('The counter element is missing from the document');
  }

  setupCounter(counter);
}
